### ISSUE TITLE
希望添加自动化批量生成功能

### ISSUE THREAD

**Issue by YutianGitHub** [zjrwtx/SFT-data-builder#1]
比如输入一批文件地址，依次生成内容，自动保存。

**Comment by zjrwtx** [comment]
感谢建议 我本来也有此打算 等后期的算法框架搭建后一部分应该就会做的

**Comment by zjrwtx** [comment]
> 比如输入一批文件地址，依次生成内容，自动保存。
已经加上了！！！增加了批量url自动化合成数据的新功能与页面

https://github.com/zjrwtx/SFT-data-builder/pull/2
