### ISSUE TITLE
AI响应生成失败: API 请求失败: 404

### ISSUE THREAD

**Issue by abchbx** [zjrwtx/SFT-data-builder#11]
老师，您好。  我在调用API的时候显示请求失败。
![image](https://github.com/user-attachments/assets/1e339117-3359-4e80-9126-5b850c657ede)

**Comment by zjrwtx** [comment]
你好 请问选的什么模型？填是glm的key了吗

**Comment by K1ra2vt** [comment]
我也遇到了这个问题，我使用的是deepseek-chat模型

**Comment by K1ra2vt** [comment]
> 老师，您好。 我在调用API的时候显示请求失败。 ![image](https://private-user-images.githubusercontent.com/20251572/390293441-1e339117-3359-4e80-9126-5b850c657ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzMyNDksIm5iZiI6MTczMzM3Mjk0OSwicGF0aCI6Ii8yMDI1MTU3Mi8zOTAyOTM0NDEtMWUzMzkxMTctMzM1OS00ZTgwLTkxMjYtNWI4NTBjNjU3ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0MjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDUxY2YxZmMxZDRlODcyODEzMDllZTY5MmI4MDQ3NDRmMjZiM2NkNGZjNmRjMGJmOWEwNGU1ZTRiODk4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IrFdiXA41QDplUKHbtAlOizg21JXW3WxV33rOMET_Rs)

我猜测可能是你没有设置IP白名单

**Comment by abchbx** [comment]
> > 老师，您好。 我在调用API的时候显示请求失败。 ![image](https://private-user-images.githubusercontent.com/20251572/390293441-1e339117-3359-4e80-9126-5b850c657ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzMyNDksIm5iZiI6MTczMzM3Mjk0OSwicGF0aCI6Ii8yMDI1MTU3Mi8zOTAyOTM0NDEtMWUzMzkxMTctMzM1OS00ZTgwLTkxMjYtNWI4NTBjNjU3ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0MjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDUxY2YxZmMxZDRlODcyODEzMDllZTY5MmI4MDQ3NDRmMjZiM2NkNGZjNmRjMGJmOWEwNGU1ZTRiODk4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IrFdiXA41QDplUKHbtAlOizg21JXW3WxV33rOMET_Rs)
> 
> 我猜测可能是你没有设置IP白名单

图片无法显示，不是ip的问题，是url，一般调用我只用写到v4.这个要写到chat/completions
